# Generated by Django 4.2.13 on 2024-07-09 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 7, 9, 17, 2, 27, 332715, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
